# Hivemoot Governance Configuration
# The bees are caffeinated ☕ - shorter cycles for bootstrap velocity

governance:
  discussionDurationMinutes: 360  # 6 hours (default: 1440 = 24h)
  votingDurationMinutes: 360      # 6 hours (default: 1440 = 24h)
